- name: Demo on AWS SSM parameter pull
  hosts: all
  tasks:
  - name: Lookup ssm parameter store in specified region
    ansible.builtin.debug: msg="{{ lookup('amazon.aws.aws_ssm', 'sample', region='us-east-1' ) }}"